// COMPETITIONS ACTIONS

export const GET_CURRENT_COMPETITION = "GET_CURRENT_COMPETITION";

export const GET_COMPETITIONS_DATA = "GET_COMPETITIONS_DATA";
export const CHANGE_COMPETITIONS_PAGE = "CHANGE_COMPETITIONS_PAGE"

// GLOBALSETTINGS ACTIONS

export const CHANGE_THEME = "CHANGE_THEME";