// TEAMS

export const GET_TEAMS_DATA = "GET_TEAMS_DATA";
export const SET_TEAMS_DATA = "SET_TEAMS_DATA";
export const SET_TEAMS_LOADING = "SET_TEAMS_LOADING";
export const SET_TEAMS_ERROR = "SET_TEAMS_ERROR";
export const CHANGE_TEAMS_PAGE = "CHANGE_TEAMS_PAGE";
export const SET_TEAMS_PAGE = "SET_TEAMS_PAGE";

// current team matches

export const GET_CURRENT_TEAM_MATCHES = "GET_CURRENT_TEAM_MATCHES";
export const SET_CURRENT_TEAM = "SET_CURRENT_TEAM";
export const SET_CURRENT_TEAM_ERROR = "SET_CURRENT_TEAM_ERROR";
export const SET_CURRENT_TEAM_LOADING = "SET_CURRENT_TEAM_LOADING";
export const CHANGE_CURRENT_TEAM_PAGE = "CHANGE_CURRENT_TEAM_PAGE";
export const SET_CURRENT_TEAM_PAGE = "SET_CURRENT_TEAM_PAGE";
export const CLEAR_CURRENT_TEAM = "CLEAR_CURRENT_TEAM";

// team by id data

export const SET_TEAM_BY_ID = "SET_TEAM_BY_ID";
export const SET_TEAM_BY_ID_LOADING = "SET_TEAM_BY_ID_LOADING";
export const SET_TEAM_BY_ID_ERROR = "SET_TEAM_BY_ID_ERROR";
export const CLEAR_TEAM_BY_ID = "CLEAR_TEAM_BY_ID";