// COMPETITIONS ACTIONS

export const GET_COMPETITIONS_DATA = "GET_COMPETITIONS_DATA";
export const SET_COMPETITIONS = "SET_COMPETITIONS";
export const SET_COMPETITIONS_LOADING = "SET_COMPETITIONS_LOADING";
export const SET_COMPETITIONS_ERROR = "SET_COMPETITIONS_ERROR";

// CURRENT COMPETITION

export const GET_CURRENT_COMPETITION = "GET_CURRENT_COMPETITION";
export const SET_CURRENT_COMPETITION = "SET_CURRENT_COMPETITION";
export const SET_CURRENT_COMPETITION_ERROR = "SET_CURRENT_COMPETITION_ERROR";
export const SET_CURRENT_COMPETITION_LOADING = "SET_CURRENT_COMPETITION_LOADING";
export const CLEAR_CURRENT_COMPETITION = "CLEAR_CURRENT_COMPETITION";
